services:
  postgres:
    image: postgres:17.5-alpine3.21
    container_name: pna-postgres
    volumes:
      - pna-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: adhitamafikridev
      POSTGRES_PASSWORD: adhitamafikridev
      POSTGRES_DB: pna-postgres

  couchdb:
    image: couchdb:3.4.3
    container_name: pna-couchdb
    volumes:
      - pna-couchdb-data:/opt/couchdb/data
    environment:
      COUCHDB_USER: adhitamafikridev
      COUCHDB_PASSWORD: adhitamafikridev

networks:
  pna-backend-network:

volumes:
  pna-postgres-data:
  pna-couchdb-data:
