# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello from offline-notes-app-backend!

dotenv: [.env]

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  service_up:
    desc: Run docker compose up
    cmds:
      - echo "Starting services with APP_ENV={{.APP_ENV}}"
      - docker compose up --build -d

  service_down:
    desc: Run docker compose down
    cmds:
      - docker compose down
